# Generated by Django 3.1.2 on 2020-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=50)),
                ('upass', models.CharField(max_length=15)),
                ('uemail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
